name: TerrainLoader
main: TerrainLoader\Loader
version: 1.0
api: [2.0.0, 3.0.1, 3.0.0]
author: Kaidorix
 
commands:
  ".load":
    default: op
    description: "Loading a terrain fragments from .terra file."
